name: stated
description: A neat set of tools aimed at making the state management easier.

version: 3.1.7
homepage: https://swipelab.co/
repository: https://github.com/swipelab/stated

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter